#[derive(Debug)]
pub struct YourModel {
    pub id: String, 
    pub uid: String,
    pub adjdate: String,
    pub adjtype: String,
    pub remitter: String,
    pub beneficiery: String,
    pub response: String,
    pub txndate: String,
    pub txntime: String,
    pub rrn: String,
    pub terminalid: String,
    pub ben_mobile_no: String,
    pub rem_mobile_no: String,
    pub chbdate: String,
    pub chbref: String,
    pub txnamount: String,
    pub adjamount: String,
    pub rem_payee_psp_fee: String,
    pub ben_fee: String,
    pub ben_fee_sw: String,
    pub adjfee: String,
    pub npcifee: String,
    pub remfeetax: String,
    pub benfeetax: String,
    pub npcitax: String,
    pub adjref: String,
    pub bankadjref: String,
    pub adjproof: String,
    pub compensation_amount: String,
    pub adjustment_raised_time: String,
    pub no_of_days_for_penalty: String,
    pub shdt73: String,
    pub shdt74: String,
    pub shdt75: String,
    pub shdt76: String,
    pub shdt77: String,
    pub transaction_type: String,
    pub transaction_indicator: String,
    pub beneficiary_account_number: String,
    pub remitter_account_number: String,
    pub aadhar_number: String,
    pub mobile_number: String,
    pub payer_psp: String,
    pub payee_psp: String,
    pub upi_transaction_id: String,
    pub virtual_address: String,
    pub dispute_flag: String,
    pub reason_code: String,
    pub mcc: String,
    pub originating_channel: String,
}

impl YourModel {
    pub fn new(id: String, uid: String, adjdate: String, adjtype: String, remitter: String, beneficiery: String, response: String, txndate: String, txntime: String, rrn: String, terminalid: String, ben_mobile_no: String, rem_mobile_no: String, chbdate: String, chbref: String, txnamount: String, adjamount: String, rem_payee_psp_fee: String, ben_fee: String, ben_fee_sw: String, adjfee: String, npcifee: String, remfeetax: String, benfeetax: String, npcitax: String, adjref: String, bankadjref: String, adjproof: String, compensation_amount: String, adjustment_raised_time: String, no_of_days_for_penalty: String, shdt73: String, shdt74: String, shdt75: String, shdt76: String, shdt77: String, transaction_type: String, transaction_indicator: String, beneficiary_account_number: String, remitter_account_number: String, aadhar_number: String, mobile_number: String, payer_psp: String, payee_psp: String, upi_transaction_id: String, virtual_address: String, dispute_flag: String, reason_code: String, mcc: String, originating_channel: String) -> Self {
        YourModel {
            id,
            uid,
            adjdate,
            adjtype,
            remitter,
            beneficiery,
            response,
            txndate,
            txntime,
            rrn,
            terminalid,
            ben_mobile_no,
            rem_mobile_no,
            chbdate,
            chbref,
            txnamount,
            adjamount,
            rem_payee_psp_fee,
            ben_fee,
            ben_fee_sw,
            adjfee,
            npcifee,
            remfeetax,
            benfeetax,
            npcitax,
            adjref,
            bankadjref,
            adjproof,
            compensation_amount,
            adjustment_raised_time,
            no_of_days_for_penalty,
            shdt73,
            shdt74,
            shdt75,
            shdt76,
            shdt77,
            transaction_type,
            transaction_indicator,
            beneficiary_account_number,
            remitter_account_number,
            aadhar_number,
            mobile_number,
            payer_psp,
            payee_psp,
            upi_transaction_id,
            virtual_address,
            dispute_flag,
            reason_code,
            mcc,
            originating_channel
        }
    }
}

#[derive(Debug)]
pub struct MyModel {
    pub id: String,
    pub uid: String,
    pub adjdate: String,
    pub adjtype: String,
    pub remitter: String,
    pub beneficiery: String,
    pub response: String,
    pub txndate: String,
    pub txntime: String,
    pub rrn: String,
    pub terminalid: String,
    pub ben_mobile_no: String,
    pub rem_mobile_no: String,
    pub chbdate: String,
    pub chbref: String,
    pub txnamount: String,
    pub adjamount: String,
    pub rem_payee_psp_fee: String,
    pub ben_fee: String,
    pub ben_fee_sw: String,
    pub adjfee: String,
    pub npcifee: String,
    pub remfeetax: String,
    pub benfeetax: String,
    pub npcitax: String,
    pub adjref: String,
    pub bankadjref: String,
    pub adjproof: String,
    pub compensation_amount: String,
    pub adjustment_raised_time: String,
    pub no_of_days_for_penalty: String,
    pub shdt73: String,
    pub shdt74: String,
    pub shdt75: String,
    pub shdt76: String,
    pub shdt77: String,
    pub transaction_type: String,
    pub transaction_indicator: String,
    pub beneficiary_account_number: String,
    pub remitter_account_number: String,
    pub aadhar_number: String,
    pub mobile_number: String,
    pub payer_psp: String,
    pub payee_psp: String,
    pub upi_transaction_id: String,
    pub virtual_address: String,
    pub dispute_flag: String,
    pub reason_code: String,
    pub mcc: String,
    pub originating_channel: String,
    // Add more fields as needed
}